### ISSUE TITLE
Wait until SSH is ready

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-terraform#17]
Current version of the playbooks assumes that host is up and client can SSH into. This is not always the case in the cloud.

Terraform starts the virtual machine. It takes some time (20-60s) until the running vm exposes SSH port. Ansible should wait until the SSH port is available.

To achieve this I am going to add first task to each major role that `wait_for` the port 22 to be open.

**Comment by ArseniiPetrovich** [comment]
As for the upcoming PR Ansible plays launch VMs through Terraform which, actually, waits until VMs are ready before returning control to the Ansible. Consequently, this issue is not actual anymore.

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
