### ISSUE TITLE
Use dynamic inventory

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-terraform#18]
Current version uses static hosts file generated from the Terraform template. The better approach is to use dynamic script returning instances data from the Azure API. The script is documented at [Ansible][1] and [Microsoft][2] sites.

Each instance has tags like 

```lang=YAML
- env: sokol
  role: bootnode
```

Azure inventory allows one to reference groups of instances based on these tags in the Ansible playbooks.

[1]: http://docs.ansible.com/ansible/latest/guide_azure.html
[2]: https://docs.microsoft.com/en-us/azure/ansible/ansible-manage-azure-dynamic-inventories

**Comment by ArseniiPetrovich** [comment]
As for now we've decided to create a jinja2 template, that is generating `hosts` file from the current play inventory. Template is used as the last play in the `build` playbook, so the generated `hosts` file can be freely used during the tests, destroy and any other job.

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
