### ISSUE TITLE
High-level overview of the ceremony

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-terraform#24]
I want this issue to be a kind of todo-list for the things we need to cover to automate the ceremony and open questions we might have.
Full instruction is available at https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup

### Ceremony in-brief
- [x] generate Master of Ceremony (MoC) key
- [x] generate bytecode for the consensus contract - clone https://github.com/poanetwork/poa-network-consensus-contracts, run `poa-bytecode.js` script, using MoC key as parameter
- [x] prepare `spec.json`, things to update:
    * network name
    * network id
    * MoC address (the one with a large amount of tokens)
    * contract bytecode
    * other... (need to have some kind of template)
- [x] launch netstats node (requires `netstats secret`)
- [x] launch explorer node
- [x] create a new empty `bootnodes.txt`
- [x] launch bootnodes
- [x] put bootnodes' enodes into `bootnodes.txt`, update local copies of bootnodes.txt on the nodes
- [x] launch MoC node
- [x] on MoC node, deploy secondary contracts of the consensus to the network. This step requires temporal unlocking of MoC node by editing the node.toml file 
- [ ] ~create a server to host dapps (maybe not need this for now)~
- [x] on MoC node generate validators initial keys. These keys need to be stored somewhere.
- [x] convert initial keys into production keys (mining key, payout key, voting key). For a real network this is done via dapp, however it can be automated via script for now
- [x] use production keys to launch validator nodes
- [x] combine several bootnodes into load-balancer (how to deal with ssl certificates here?)
- [x] do basic tests to check that network is functioning

### Input parameters (provided to the terraform script by the user)
  * network name
  * network id
  * template of spec.json (should have a default)
  * required number of bootnodes (defaults to 1)
  * required number of bootnodes to put in load-balancer (defaults to 1)
  * required number of initial keys to generate (defaults to 1)
  * required number of initial keys to convert to production keys (defaults to 1)
  * required number of validator nodes to launch (defaults to 1)
  * netstats secret (optional)

### Internal parameters (terraform needs to generate)
  * MoC key
  * netstats secret

### Parameters that should be stored in a database
  * MoC key
  * netstats secret (if not provided as input parameter)
  * spec.json
  * bootnodes.txt
  * generated initial keys
  * generated production keys

### Useful tools
Manipulation on eth keys (creating, converting keystore files <-> private keys, etc) can be done using [keythereum](https://github.com/ethereumjs/keythereum)

**Comment by ArseniiPetrovich** [comment]
As for the second step I've found that poa-bytecode.js accepts not the generated key, but the address. When I've tried to pass generated key here I got the `capitalization checksum test failed` error.

**Comment by phahulin** [comment]
DApps will be addressed in a separate issue, since it requires some updates of dapps themselves in terms of configuration files.

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
