### ISSUE TITLE
jumbox with prerequsites

### ISSUE THREAD

**Issue by Ykisialiou** [poanetwork/deployment-terraform#27]
We have a lot of dependencies to install locally before deployment playbooks  are ready to run. 
Looks like it's better to create jumbox host with terraform, and install everything there (pip and npm them self, all their packages etc) to avoid dependency hell and necessity to support any OS, user can have locally. 

Another option I can see here, is to create and provide container with all dependencies ready.

**Comment by phahulin** [comment]
I think container is a good idea.
But we should still be clear about what we install. So container shouldn't be _the only way_ to run deployment, but a ready-to-use solution in case user is having troubles/doesn't want to install required dependencies.

**Comment by phahulin** [comment]
So what I mean is - dependencies should not be installed by the playbooks. But if user doesn't want to install them, he can use container where they are preinstalled.

**Comment by ArseniiPetrovich** [comment]
We've deployed a [container](https://hub.docker.com/r/poanetwork/terraform-prep/) with all the prerequisites for `deployment-terraform` scripts. Also, we've transferred all the prerequisited generating process to the MoC node, which is also will be considered as a jumpbox from now on.

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
