### ISSUE TITLE
Specifying ssh keys

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-terraform#3]
Please clarify about ssh keys usage for a case of non-standard keypair name (not `id_rsa`). Is setting `ansible_ssh_private_key_file`, `ssh_public_key` and `ssh_public_key_ansible` in `terraform.tfvars` enough?

Also, there are some defaults that look like tests, e.g.
https://github.com/poanetwork/deployment-terraform/blob/master/terraform/azure/variables.tf#L8

**Comment by lexsys27** [comment]
- fixed in 0f4f1bf
