### ISSUE TITLE
Check absible 2.6 compatability

### ISSUE THREAD

**Issue by Ykisialiou** [poanetwork/deployment-terraform#31]
Ansible 2.6 is pretty new, but all development was under 2.4 and 2.5. 2.6 should be tested to avoid bugs (looks like no fafactoring needed, just regression testing).

**Comment by ArseniiPetrovich** [comment]
Current version is fully compatible with ansible 2.6. We need to upgrade our docker image, since 2.6 has an imortant bug fixing for `azure_rm_storageaccount` module.

**Comment by phahulin** [comment]
Docker image is upgraded via https://github.com/poanetwork/deployment-terraform/pull/44
