### ISSUE TITLE
Setting node parameters

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-terraform#4]
Please make `vm_size` and resource group name configurable variables.

Is it possible to create and manage multiple deployments under the same azure account? After I've created the first deployment `terraform plan` returns `No changes. Infrastructure is up-to-date.` If yes, which parameter is used to separate them, could it also be made configurable?

**Comment by lexsys27** [comment]
- managing multiple deployments: added to documentation in 501a541dc
- variables added in 1f7f3dbb542 and daf4700 accordingly
