### ISSUE TITLE
More detailed README

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-terraform#42]
Update README to describe in more details:

1. what are the azure authentication options, when to choose which
2. what are the possible state storage options, when to choose which
3. mention that user may want to create azure resource group, before running the deployment, and where to set its name
4. how to use custom spec.json and custom playbook options (e.g. how to use custom parity binary via `PARITY_BIN_LOC`, `PARITY_BIN_SHA256`)
5. how to specify which ssh key to use

**Comment by phahulin** [comment]
Done in #45 and #50

**Comment by ArseniiPetrovich** [comment]
Azure README's list still not properly formatted.
