### ISSUE TITLE
Two copies of deployment playbooks

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-terraform#5]
Currently deployment automation uses a separate copy of `deployment-playbooks` as the original version is focused on AWS cloud. There is also the requirement the user can run playbooks without Terraform.

Maintaining two copies will require manual sync between them and is not convenient.

@igorbarinov @phahulin what are your thoughts about this issue?

**result**: Terraform configures instances using code from `terraform-integration` branch from `poanetwork/deployment-playbooks` repository

## Plan

- [x] create branch `terraform-integration` from `master` in `poanetwork/deployment-playbooks`
- [x] add git sub-module tracking this branch
- [x] rebase changes from the `playbooks` directory to the `terraform-integration` branch
- [ ] switch to the `poanetwork/deployment-playbooks` repo
- [ ] delete `playbooks` firectory

**Comment by lexsys27** [comment]
Playbooks contained AWS resources - I deleted them.

Also it is possible to generate playbooks group variables from Terraform templates.

In all other cases the playbooks are identical to ones used for configuration management on other cloud providers.

**Comment by lexsys27** [comment]
1. [AWS variables][1] are inside the node template
2. [Some roles][2] configure AWS resources

We can look at this issue from two viewpoints - workaround and long-term fix. As quick fix manual sync will do. As long-term solution I would suggest keeping all the deployment automation in the single repo. This includes Terraform scripts for the cloud providers (Azure, AWS, GCP), Ansible playbooks for node configuration, Jenkins pipelines, integration and unit tests for deployment automation.

Ansible playbooks should assume the hosts and cloud resources are already provisioned. It may be separate ansible script for the near future and Terraform script at the next stage.

Terraform must template only the inventory and group_vars files. This way ansible playbooks will be usable without Terraform e.g. when deploying on the bare metal. Developer can specify configuration in a single place - Terraform vars while provisioning with Terraform or group_vars without it. 

[1]: https://github.com/poanetwork/deployment-playbooks/blob/master/group_vars/bootnode.example#L1-L3
[2]: https://github.com/poanetwork/deployment-playbooks/blob/master/roles/bootnode-access/tasks/main.yml#L6-L8

**Comment by lexsys27** [comment]
My idea is to create a parallel branch in `deployment-playbooks` called `terraform`. In this branch I will delete AWS-related code and do some cloud-related changes. For example, I don't need to run `update_system` task as I start from `Ubuntu:latest` image. This image is upgraded by its maintainer so I get the fresh version each time I run provisioning.

This setup will allow me to cherry-pick commits from the `master` branch. In case I do changes that are useful for all the playbooks I will do PR against `master`.

**Comment by phahulin** [comment]
Great, I think that's a good idea

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-terraform/pull/26
