### ISSUE TITLE
Resource group should be manually created before running the script

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-terraform#6]
or should the script create the resource group and then all the resources inside of it?

Currently the first scenario is implemented but I would like to hear your thoughts which way is the best.

**Comment by phahulin** [comment]
I think script should create all entities by itself, including resource groups. Are there any drawbacks or tricks? How can subscription be provided to the script?

**Comment by lexsys27** [comment]
no, this change is pretty straightforward.

You select a subscription when login to the azure cli. On CI/CD server there will be service account authentication.
